version: "3"

services:
  rabbit:
    image: "rabbitmq:3-management"
    volumes:
     - ./data/db:/var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: "redis"
    volumes:
      - ./data/db2:/data
    ports:
      - "6379:6379"
